# Netlify Build & Redirect Configuration

[build]
  command = "npm install && npm run build"
  functions = "server/"
  publish = "dist/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/api/:splat"
  status = 200